title: Pentoo
description: > # this means to ignore newlines until "baseurl:"
  twitter: <a href="https://twitter.com/pentoo_linux">@pentoo_linux</a><br><br><a href="http://pentoo.ch"><img src="https://avatars0.githubusercontent.com/u/6411603?v=3&s=200"></a><br>

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-minimal
