title: " "
description: > # this means to ignore newlines until "baseurl:"
  twitter: <a href="https://twitter.com/pentoo_linux">@pentoo_linux</a><br>
  docs: <a href="https://github.com/pentoo/pentoo-overlay/wiki">pentoo wiki</a><br><br>
  irc: <a href="http://webchat.freenode.net/?channels=pentoo">#pentoo</a><br>
  blog: <a href="http://pentoo.blogspot.com">pentoo.blogspot.com</a><br><a href="http://pentoo.ch"><img src="https://avatars0.githubusercontent.com/u/6411603?v=3&s=200"></a><br>download: <a href="https://pentoo.ch/isos/">stable</a><br>beta download: <a href="https://pentoo.ch/isos/Beta/">beta</a><br>

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_downloads: "false"
google_analytics: 

theme: jekyll-theme-minimal
